# hugo server --minify --themesDir ../.. --baseURL=http://0.0.0.0:1313/theme/hugo-book/

baseURL = 'https://nortek-references.netlify.app/'
title = 'Nortek references'
theme = 'hugo-book'
languageCode = "en-us"

[params]
  BookSection = "*"